version: "3"

services:
  rust_nano_s_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/app
    ports:
      - "1234:1234"
      - "1236:1236"
      - "5000:5000"
      - "9999:9999"
      - "40000:40000"
      - "41000:41000"
      - "42000:42000"
      - "8100:8100"
